//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Comdata.RealTimeOnline0103.Models;
<<<<<<< HEAD
using System.CodeDom.Compiler;
=======
>>>>>>> releases/v1.0.0
using System.ServiceModel;
using System.Threading.Tasks;

namespace Comdata.RealTimeOnline0103
{
<<<<<<< HEAD
    [GeneratedCode("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContract(Namespace="http://cows0103.comdata.com", ConfigurationName="Comdata.RealTimeOnline0103")]
    public interface IRealTimeOnline0103
    {
        [OperationContract(Action = "cardBlockUnblock", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardBlockUnblockResponseBody> CardBlockUnblockAsync(CardBlockUnblockRequestBody request);

        [OperationContract(Action = "cardInquiry", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardInquiryResponseV01Body> CardInquiryAsync(CardInquiryRequestV01Body request);

        [OperationContract(Action = "cardInquiryV02", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardInquiryResponseV02Body> CardInquiryV02Async(CardInquiryRequestV02Body request);

        [OperationContract(Action = "cardInquiryV03", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardInquiryResponseV03Body> CardInquiryV03Async(CardInquiryRequestV03Body request);

        [OperationContract(Action = "cardMoveMaintenance", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardMoveMaintenanceResponseBody> CardMoveMaintenanceAsync(CardMoveMaintenanceRequestBody request);

        [OperationContract(Action = "cardUpdate", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardUpdateResponseV01Body> CardUpdateAsync(CardUpdateRequestV01Body request);

        [OperationContract(Action = "cardUpdateV02", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardUpdateResponseV02Body> CardUpdateV02Async(CardUpdateRequestV02Body request);

        [OperationContract(Action = "cardUpdateV03", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [ServiceContractAttribute(Namespace="http://cows0103.comdata.com", ConfigurationName="Comdata.RealTimeOnline0103")]
    public interface IRealTimeOnline0103
    {
        [OperationContractAttribute(Action = "cardBlockUnblock", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardBlockUnblockResponseBody> CardBlockUnblockAsync(CardBlockUnblockRequestBody request);

        [OperationContractAttribute(Action = "cardInquiry", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardInquiryResponseV01Body> CardInquiryAsync(CardInquiryRequestV01Body request);

        [OperationContractAttribute(Action = "cardInquiryV02", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardInquiryResponseV02Body> CardInquiryV02Async(CardInquiryRequestV02Body request);

        [OperationContractAttribute(Action = "cardInquiryV03", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardInquiryResponseV03Body> CardInquiryV03Async(CardInquiryRequestV03Body request);

        [OperationContractAttribute(Action = "cardMoveMaintenance", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardMoveMaintenanceResponseBody> CardMoveMaintenanceAsync(CardMoveMaintenanceRequestBody request);

        [OperationContractAttribute(Action = "cardUpdate", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardUpdateResponseV01Body> CardUpdateAsync(CardUpdateRequestV01Body request);

        [OperationContractAttribute(Action = "cardUpdateV02", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardUpdateResponseV02Body> CardUpdateV02Async(CardUpdateRequestV02Body request);

        [OperationContractAttribute(Action = "cardUpdateV03", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<CardUpdateResponseV03Body> CardUpdateV03Async(CardUpdateRequestV03Body request);



<<<<<<< HEAD
        [OperationContract(Action = "DirectDepositAddUpdate", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<DirectDepositAddUpdateResponseBody> DirectDepositAddUpdateAsync(DirectDepositAddUpdateRequestBody request);

        [OperationContract(Action = "DirectDepositInquiry", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "DirectDepositAddUpdate", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<DirectDepositAddUpdateResponseBody> DirectDepositAddUpdateAsync(DirectDepositAddUpdateRequestBody request);

        [OperationContractAttribute(Action = "DirectDepositInquiry", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<DirectDepositInquiryResponseBody> DirectDepositInquiryAsync(DirectDepositInquiryRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action="expressCheckInquiry", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<ExpressCheckInquiryResponseBody> ExpressCheckInquiryAsync(ExpressCheckInquiryRequestBody request);
        
        [OperationContract(Action="expressCheckIssue", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<ExpressCheckIssueResponseBody> ExpressCheckIssueAsync(ExpressCheckIssueRequestBody request);
        
        [OperationContract(Action="expressCheckMaintenance", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<ExpressCheckMaintenanceResponseBody> ExpressCheckMaintenanceAsync(ExpressCheckMaintenanceRequestBody request);

        [OperationContract(Action = "expressCheckBatch", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<ExpressCheckBatchResponseBody> ExpressCheckBatchAsync(ExpressCheckBatchRequestBody request);

        [OperationContract(Action = "expressCheckRetrieval", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action="expressCheckInquiry", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<ExpressCheckInquiryResponseBody> ExpressCheckInquiryAsync(ExpressCheckInquiryRequestBody request);
        
        [OperationContractAttribute(Action="expressCheckIssue", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<ExpressCheckIssueResponseBody> ExpressCheckIssueAsync(ExpressCheckIssueRequestBody request);
        
        [OperationContractAttribute(Action="expressCheckMaintenance", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<ExpressCheckMaintenanceResponseBody> ExpressCheckMaintenanceAsync(ExpressCheckMaintenanceRequestBody request);

        [OperationContractAttribute(Action = "expressCheckBatch", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<ExpressCheckBatchResponseBody> ExpressCheckBatchAsync(ExpressCheckBatchRequestBody request);

        [OperationContractAttribute(Action = "expressCheckRetrieval", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<ExpressCheckRetrievalResponseBody> ExpressCheckRetrievalAsync(ExpressCheckRetrievalRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action="limitedNetworkByCardUpdate", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
=======
        [OperationContractAttribute(Action="limitedNetworkByCardUpdate", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
>>>>>>> releases/v1.0.0
        Task<LimitedNetworkByCardUpdateResponseBody> LimitedNetworkByCardUpdateAsync(LimitedNetworkByCardUpdateRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "locationMaintenance", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "locationMaintenance", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<LocationMaintenanceResponseBody> LocationMaintenanceAsync(LocationMaintenanceRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action="loadMoney", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<LoadMoneyResponseBody> LoadMoneyAsync(LoadMoneyRequestBody request);
        
        [OperationContract(Action="loadMoneyComchek", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
        Task<LoadMoneyComchekResponseBody> LoadMoneyComchekAsync(LoadMoneyComchekRequestBody request);
        
        [OperationContract(Action="loadMoneyCancel", ReplyAction="*")]
        [XmlSerializerFormat(SupportFaults=true)]
=======
        [OperationContractAttribute(Action="loadMoney", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<LoadMoneyResponseBody> LoadMoneyAsync(LoadMoneyRequestBody request);
        
        [OperationContractAttribute(Action="loadMoneyComchek", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<LoadMoneyComchekResponseBody> LoadMoneyComchekAsync(LoadMoneyComchekRequestBody request);
        
        [OperationContractAttribute(Action="loadMoneyCancel", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
>>>>>>> releases/v1.0.0
        Task<LoadMoneyCancelResponseBody> LoadMoneyCancelAsync(LoadMoneyCancelRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "pinSet", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "pinSet", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<PinSetResponseBody> PinSetAsync(PinSetRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "pinReset", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "pinReset", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<PinResetResponseBody> PinResetAsync(PinResetRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "trackCardShipmentStatus", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "trackCardShipmentStatus", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<TrackCardShipmentResponseBody> TrackCardShipmentStatusAsync(TrackCardShipmentRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "transferToBank", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<TransferToBankResponseBody> TransferToBankAsync(TransferToBankRequestBody request);

        [OperationContract(Action = "transferMaintenance", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<CardTransferMaintenanceResponseBody> TransferMaintenanceAsync(CardTransferMaintenanceRequestBody request);

        [OperationContract(Action = "transferMaintenanceByCardtoken", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "transferToBank", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<TransferToBankResponseBody> TransferToBankAsync(TransferToBankRequestBody request);

        [OperationContractAttribute(Action = "transferMaintenance", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<CardTransferMaintenanceResponseBody> TransferMaintenanceAsync(CardTransferMaintenanceRequestBody request);

        [OperationContractAttribute(Action = "transferMaintenanceByCardtoken", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<TransferMaintenanceByCardtokenResponseBody> TransferMaintenanceByCardtokenAsync(TransferMaintenanceByCardtokenRequestBody request);



<<<<<<< HEAD
        [OperationContract(Action = "virtualCardAdd", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<VirtualCardAddResponseBody> VirtualCardAddAsync(VirtualCardAddRequestBody request);

        //[OperationContract(Action = "virtualCardAddAsync", ReplyAction = "*")]
        //[XmlSerializerFormat(SupportFaults = true)]
        //Task<VirtualCardAddAsyncResponse> VirtualCardAddAsync(VirtualCardAddAsyncRequest request);

        [OperationContract(Action = "virtualCardInquiry", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<VirtualCardInquiryResponseBody> VirtualCardInquiryAsync(VirtualCardInquiryRequestBody request);

        //[OperationContract(Action = "virtualCardInquiryAsync", ReplyAction = "*")]
        //[XmlSerializerFormat(SupportFaults = true)]
        //Task<VirtualCardInquiryAsyncResponse> VirtualCardInquiryAsync(VirtualCardInquiryAsyncRequest request);

        [OperationContract(Action = "virtualCardUpdate", ReplyAction = "*")]
        Task<VirtualCardUpdateResponseBody> VirtualCardUpdateAsync(VirtualCardUpdateRequestBody request);

        //[OperationContract(Action = "virtualCardUpdateAsync", ReplyAction = "*")]
        //[XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "virtualCardAdd", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<VirtualCardAddResponseBody> VirtualCardAddAsync(VirtualCardAddRequestBody request);

        //[OperationContractAttribute(Action = "virtualCardAddAsync", ReplyAction = "*")]
        //[XmlSerializerFormatAttribute(SupportFaults = true)]
        //Task<VirtualCardAddAsyncResponse> VirtualCardAddAsync(VirtualCardAddAsyncRequest request);

        [OperationContractAttribute(Action = "virtualCardInquiry", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<VirtualCardInquiryResponseBody> VirtualCardInquiryAsync(VirtualCardInquiryRequestBody request);

        //[OperationContractAttribute(Action = "virtualCardInquiryAsync", ReplyAction = "*")]
        //[XmlSerializerFormatAttribute(SupportFaults = true)]
        //Task<VirtualCardInquiryAsyncResponse> VirtualCardInquiryAsync(VirtualCardInquiryAsyncRequest request);

        [OperationContractAttribute(Action = "virtualCardUpdate", ReplyAction = "*")]
        Task<VirtualCardUpdateResponseBody> VirtualCardUpdateAsync(VirtualCardUpdateRequestBody request);

        //[OperationContractAttribute(Action = "virtualCardUpdateAsync", ReplyAction = "*")]
        //[XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        //Task<VirtualCardUpdateAsyncResponse> VirtualCardUpdateAsync(VirtualCardUpdateAsyncRequest request);



<<<<<<< HEAD
        [OperationContract(Action = "virtualComchekAdd", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<VirtualComchekAddResponseBody> VirtualComchekAddAsync(VirtualComchekAddRequestBody request);

        [OperationContract(Action = "virtualComchekInquiry", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
        Task<VirtualComchekInquiryResponseBody> VirtualComchekInquiryAsync(VirtualComchekInquiryRequestBody request);

        [OperationContract(Action = "virtualComchekUpdate", ReplyAction = "*")]
        [XmlSerializerFormat(SupportFaults = true)]
=======
        [OperationContractAttribute(Action = "virtualComchekAdd", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<VirtualComchekAddResponseBody> VirtualComchekAddAsync(VirtualComchekAddRequestBody request);

        [OperationContractAttribute(Action = "virtualComchekInquiry", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
        Task<VirtualComchekInquiryResponseBody> VirtualComchekInquiryAsync(VirtualComchekInquiryRequestBody request);

        [OperationContractAttribute(Action = "virtualComchekUpdate", ReplyAction = "*")]
        [XmlSerializerFormatAttribute(SupportFaults = true)]
>>>>>>> releases/v1.0.0
        Task<VirtualComchekUpdateResponseBody> VirtualComchekUpdateAsync(VirtualComchekUpdateRequestBody request);
    }    
}
